# Generated by Django 6.1 on 2026-08-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pesticides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="crops/")),
                ("description", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="crop",
            name="season",
        ),
        migrations.RemoveField(
            model_name="crop",
            name="soil",
        ),
    ]
