# Generated by Django 6.1 on 2026-08-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0002_pesticides_remove_crop_season_remove_crop_soil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fertilizer",
            name="image",
            field=models.ImageField(upload_to="Fertilizer/"),
        ),
        migrations.AlterField(
            model_name="pesticides",
            name="image",
            field=models.ImageField(upload_to="Pesticides/"),
        ),
    ]
