# Generated by Django 6.1 on 2026-08-26 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0003_alter_fertilizer_image_alter_pesticides_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crop",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="crop",
            name="description",
        ),
        migrations.AddField(
            model_name="crop",
            name="growth_duration_days",
            field=models.PositiveIntegerField(
                blank=True, help_text="Days from sowing to harvest", null=True
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="ideal_temperature",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="crop",
            name="scientific_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="crop",
            name="season",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kharif", "Kharif"),
                    ("rabi", "Rabi"),
                    ("zaid", "Zaid"),
                    ("perennial", "Perennial"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="short_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="crop",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name="crop",
            name="soil_type",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="crop",
            name="water_requirement",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="crop",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="crops/"),
        ),
        migrations.CreateModel(
            name="CropNutrition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nutrient_name", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
                ("per_quantity", models.CharField(default="100g", max_length=50)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_facts",
                        to="crops.crop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CropProducingCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("rank", models.PositiveIntegerField()),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_producers",
                        to="crops.crop",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="CropSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("order", models.IntegerField(default=0)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="crops.crop",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CropSectionPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=150)),
                ("detail", models.TextField()),
                ("order", models.IntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="crops.cropsection",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CropVariety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("origin_region", models.CharField(blank=True, max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="crop_varieties/"
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="varieties",
                        to="crops.crop",
                    ),
                ),
            ],
        ),
    ]
