# Generated by Django 6.1 on 2026-08-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0004_alter_crop_options_remove_crop_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cropproducingcountry",
            name="crop",
        ),
        migrations.RemoveField(
            model_name="cropsection",
            name="crop",
        ),
        migrations.RemoveField(
            model_name="cropsectionpoint",
            name="section",
        ),
        migrations.RemoveField(
            model_name="cropvariety",
            name="crop",
        ),
        migrations.AlterModelOptions(
            name="crop",
            options={},
        ),
        migrations.RemoveField(
            model_name="crop",
            name="growth_duration_days",
        ),
        migrations.RemoveField(
            model_name="crop",
            name="ideal_temperature",
        ),
        migrations.RemoveField(
            model_name="crop",
            name="scientific_name",
        ),
        migrations.RemoveField(
            model_name="crop",
            name="season",
        ),
        migrations.RemoveField(
            model_name="crop",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="crop",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="crop",
            name="soil_type",
        ),
        migrations.RemoveField(
            model_name="crop",
            name="water_requirement",
        ),
        migrations.AddField(
            model_name="crop",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="crop",
            name="image",
            field=models.ImageField(upload_to="crops/"),
        ),
        migrations.DeleteModel(
            name="CropNutrition",
        ),
        migrations.DeleteModel(
            name="CropProducingCountry",
        ),
        migrations.DeleteModel(
            name="CropSection",
        ),
        migrations.DeleteModel(
            name="CropSectionPoint",
        ),
        migrations.DeleteModel(
            name="CropVariety",
        ),
    ]
