# Generated by Django 6.1 on 2026-08-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0005_remove_cropproducingcountry_crop_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
