# Generated by Django 6.1 on 2026-09-30 08:31

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0007_alter_crop_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="fertilizer",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="pesticides",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
    ]
