# Generated by Django 6.1.1 on 2026-10-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0008_alter_crop_description_alter_fertilizer_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="card_desc",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="fertilizer",
            name="card_desc",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="pesticides",
            name="card_desc",
            field=models.TextField(default=""),
        ),
    ]
