# Generated by Django 6.1.1 on 2026-10-10 05:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0009_crop_card_desc_fertilizer_card_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="photo"
            ),
        ),
        migrations.AlterField(
            model_name="fertilizer",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="photo"
            ),
        ),
        migrations.AlterField(
            model_name="pesticides",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="photo"
            ),
        ),
    ]
