# Generated by Django 6.1 on 2026-08-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CropQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="crop_photos/%Y/%m/%d/")),
                (
                    "question_text",
                    models.TextField(
                        blank=True,
                        help_text="Kisan ka sawaal, jaise 'iski patti pili kyun ho rahi hai'",
                    ),
                ),
                (
                    "ai_response",
                    models.TextField(blank=True, help_text="AI ka jawaab (Hindi me)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("conversation", models.JSONField(blank=True, default=list)),
                ("farmer_name", models.CharField(blank=True, max_length=150)),
                ("location", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
