# Generated by Django 6.1.1 on 2026-10-10 05:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cropquery",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="crop_photos/%Y/%m/%d/"
            ),
        ),
    ]
